version: '3'
services:
  registry:
    platform: linux/amd64
    build: registry
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  auth-service:
    platform: linux/amd64
    build: auth-service
    ports:
      - "5001:5001"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
    depends_on:
      - registry

  movie-service:
    platform: linux/amd64
    build: movie-service
    ports:
      - "6001:6001"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/armdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=
      # - SPRING_DATASOURCE_URL=jdbc:postgresql://armdb-postgres:5432/armdb
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
    depends_on:
      - registry
      # - armdb-postgres
    # network_mode: host

  gateway:
    platform: linux/amd64
    build: gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
      - SPRING_DATA_REDIS_HOST=armdb-redis
    depends_on:
      - registry
      - armdb-redis

  # armdb-postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     - POSTGRES_DB=armdb
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  armdb-redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus

